from modules import launch_utils
from modules import shared
import json
import sys
import os


if __name__ == "__main__":
    args = shared.parser.parse_args()
    
    python = launch_utils.python

    args_history = []
    if not os.path.exists("history.json"):
        with open("history.json", "w") as f:
            json.dump([], f)
    args_history = json.load(open("history.json", "r"))
    
    launch_utils.check_environment()

    if args.check:
        try:
            os.system("git pull")
            launch_utils.prepare_packages()
        except:
            print("Failed to prepare packages")
            
        '''
        I find that every time I try to run prepare_packages(),
            it automatically generates a file called '=9.5.0'.
        It appears that the file is generated by subprocess.run(),
            in modules/launch_utils.py, line 44.
        But I tried to run os.system("pip install Pillow>=9.5.0"),
            the file '9.5.0' appeared again.
        However, if I change the requirement to Pillow or Pillow==9.5.0,
            the file '=9.5.0' will not appear.
        It might has something to do with '>='.
        I don't know why, so bellow I delete all files that start with '='.
        '''
        files = os.listdir(".")
        for file in files:
            if file[0] == "=":
                os.remove(file)
        exit()

    if args.no_history:
        print("Performing zero arguments")
        os.system(f"{python} server.py")
    
    elif len(sys.argv) == 1:
        print("Performing history arguments")
        os.system(f"{python} server.py {' '.join(args_history)}")
    
    elif len(sys.argv) > 1:
        print("Performing arguments: " + str(sys.argv[1:]))
        args_history = sys.argv[1:]
        json.dump(args_history, open("history.json", "w"))
        os.system(f"{python} server.py {' '.join(sys.argv[1:])}")