chat-instruct_command: Continue the chat dialogue below. Write a single reply for
  the character "<|character|>".
chat_style: cai-chat
dark_theme: true
default_extensions:
- character_bias
- gallery
instruction_template: Alpaca
max_new_tokens: 512
repetition_penalty: 1.1
temperature: 0.7
top_k: 20
top_p: 0.9
