temperature: 0.7
top_p: 0.9
repetition_penalty: 1.18
repetition_penalty_range: 0
character: Сюзи
name1: Вовчик
name2: Сюзи
loader: llama.cpp
model_name: Qwen2.5-14B-Instruct-Uncensored.i1-Q5_K_S.gguf
gpu_layers: 44
ctx_size: 8192
batch_size: 256
cache_type: fp16
rope_freq_base: 1000000
compress_pos_emb: 1
instruction_template: Custom (obtained from model metadata)
listen: true
auto_launch: true
share: true
flash_attn: true
cpu_memory: 0
tensor_split: ''
n_batch: 256
threads: 0
threads_batch: 0
no_mmap: false
mlock: false
no_mul_mat_q: false
alpha_value: 1
rope_scaling_type: 1
min_length: 0
max_tokens: 200
