version: "3.3"
services:
  text-generation-webui:
    build:
      context: .
      args:
        # Requirements file to use: 
        # | GPU | requirements file to use |
        # |--------|---------|
        # | NVIDIA | `requirements.txt` |
        # | AMD | `requirements_amd.txt` |
        # | CPU only | `requirements_cpu_only.txt` |
        # | Apple Intel | `requirements_apple_intel.txt` |
        # | Apple Silicon | `requirements_apple_silicon.txt` |
        # Default: requirements.txt`
        # BUILD_REQUIREMENTS: requirements.txt

        # Extension requirements to build: 
        # BUILD_EXTENSIONS: 

        # specify which cuda version your card supports: https://developer.nvidia.com/cuda-gpus
        TORCH_CUDA_ARCH_LIST: ${TORCH_CUDA_ARCH_LIST:-12.4} 
        BUILD_EXTENSIONS: ${BUILD_EXTENSIONS:-}
        APP_GID: ${APP_GID:-1000} 
        APP_UID: ${APP_UID:-1000} 
    
    user: "${APP_RUNTIME_UID:-1000}:${APP_RUNTIME_GID:-1000}"
    ports:
      
        - "${localhost:-7860}:${CONTAINER_PORT:-7860}"
        - "${localhost:-5000}:${CONTAINER_API_PORT:-5000}" 
   

    stdin_open: true
    tty: true
    volumes:
      - ./user_data:/home/app/text-generation-webui/user_data:Z
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
